### ISSUE TITLE
Fetching throws error

### ISSUE THREAD

**Issue by jordantomax** [PaulUithol/Backbone-relational#141]
I'm quite sure this is only due to my inexperience with backbone relational, but i would greatly appreciate any advice. 

I have included Backbone Relational in my application, have created a simple backbone model and collection. Regardless of whether the model extend Backbone.RelationalModel or Backbone.Model, when I call fetch on the collection, I get this error:

TypeError: 'undefined' is not an object (evaluating 'this.model.prototype.idAttribute') 

from ln.1550 of backbone.relational.js

The error only occurs when I have actual entries in the database, so I figure it may be a problem with my database schema, but I'm very new to Backbone.Relational and don't know exactly where to look. 

I don't see why fetching on a collection that has its model set to a model that is extending the standard Backbone.Model should throw an error in Backbone Relational. Any advice?

**Comment by samarthsikotara** [comment]
I am also facing the same issues. Have you solved it yet? pls let me know.
