### ISSUE TITLE
Transforming between submodels

### ISSUE THREAD

**Issue by parauchf** [PaulUithol/Backbone-relational#250]
I have a model with several subtypes.  The model has a relation to itself forming a tree structure.  Sometimes an element in the tree needs to change between types (still the same base model).

I tried implementing this with something like the following:

    transform: function(klass): {
       var json =  this.toJSON();
       _.extend(this,klass.prototype);
      this.set.apply(this,json);
      return this;
    }

But I got the dreaded "Cannot instantiate more than one Backbone.RelationalModel with the same id per type! ". 

I could delete the model and create  a new one, but I would lose the ordering of the relations which is important.  Does anyone have a good solution to transforming the models?

**Comment by bpatram** [comment]
Closing issue due to age
