### ISSUE TITLE
Collection.prototype.fetchRelated akin to SQL join

### ISSUE THREAD

**Issue by kennknowles** [PaulUithol/Backbone-relational#255]
Hello!

I cannot determine how to achieve a common pattern of bulk operation, similar to a SQL join, with Backbone-Relational. Given a collection of models, I would like to fetch all related models for a particular relation in a single request.

If you consider the Zoo example from the README, what I am describing might look like this:

```javascript
var animals = new AnimalCollection();

animals.on('reset', function() {
   animals.fetchRelated('livesIn');
});

animals.fetch();
```

This should result in exactly two requests to the server, one for all the animals, and one for all the related zoos. Note how this is for a `HasOne` relationship; it is different from the optimization that already exists for fetching all the targets of a `HasMany` relationship.

Apologies if I have missed how this is already possible, or if there is another way I ought to go about this.

-- Kenn

**Comment by bpatram** [comment]
Closing due to age
