### ISSUE TITLE
more complex relations examples

### ISSUE THREAD

**Issue by hardevine** [PaulUithol/Backbone-relational#334]
any case/example/snippet where only string type is possible for 'relatedModel' option  instead of direct reference...
relatedModelrelation.relatedModel

Required. A string that can be resolved to an object on the global scope, or a reference to a Backbone.RelationalModel.
..
??

**Comment by bpatram** [comment]
I understand this issue is 3 years old, but there are [examples on the documentation](http://backbonerelational.org/#examples) site that demonstrates using Strings rather than model references for relations.
