### ISSUE TITLE
could not extend relationalmodel class

### ISSUE THREAD

**Issue by hardevine** [PaulUithol/Backbone-relational#343]
i wanted to extend a relational model class but could not...

the extended class shows related data as 'Object' instead of 'child' (instantiated models)

i used relMode.setup() but nothing seems helpful please help..

here is a fiddle
http://jsfiddle.net/hardiv/tHD7V/

**Comment by bpatram** [comment]
Try creating the `Room` model first then the `Building` model. That way `Room` exists when you create `Building` and its relations.
