### ISSUE TITLE
redundant params when save relational model

### ISSUE THREAD

**Issue by MQuy** [PaulUithol/Backbone-relational#346]
I have post model and comment model. Post has many comment. When i fetch post completely, i fetch comment belongs to this post. And after that, i update post atrributes like upvote. i call post.save({upvote: xxx}) and i check server backbone relation pass a whole information include post(of course) and also comments' information(redundant). Is there any config to prevent that thing happen

**Comment by bpatram** [comment]
You could override your model's `toJSON` function and add the logic you need to omit certain attributes from being sent. Any options you pass to `save()` will also be passed to your `toJSON` function (through `Backbone.Sync`).
