### ISSUE TITLE
fetchRelated with a collection URL not working as expected

### ISSUE THREAD

**Issue by RobWilkinson** [PaulUithol/Backbone-relational#357]
Because fetchRelated uses an option of remove:false, unless you override with remove:true or use reset:true, you will get an extra  model with the parent record id as the id of the child. This is probably OK except when the id of the child is not the same as the id of the parent. i.e you have used keySource::A and keyDestination:B

Regards,
Rob

**Comment by bpatram** [comment]
This issue may help you #549 
This comment [specifically](http://lea.verou.me/2012/04/background-attachment-local/)
