### ISSUE TITLE
full serialization hack, access removed relations

### ISSUE THREAD

**Issue by josx** [PaulUithol/Backbone-relational#364]
I need to sync a full serialization toJSON model (waiting until this patch is included https://github.com/PaulUithol/Backbone-relational/pull/183). 
I figured out making a custom save.

```
save: function(attributes, options) {
         var instance_rel = this.get('playlist').getRelation('pieces');

        instance_rel.options.includeInJSON = true;
 
         var options = _.defaults((options||{}) , {
             success: function() {
                 instance_rel.options.includeInJSON = '_id';
             }
         });
 
        Backbone.Model.prototype.save.call(this, attributes, options);
     },
```
Thats why I need to access this model even if it is remove relations.
The problem is that when I remove relations, I cant access to the whole object.
(but if I restart my app, relational dont find relation but let me access to it).
Any clue  to solve this?

**Comment by bpatram** [comment]
Closing due to age
