### ISSUE TITLE
Backbone.Relational.store

### ISSUE THREAD

**Issue by USvER** [PaulUithol/Backbone-relational#450]
So, i had many issues like "duplicate id" and i was fixing it by finding cached models in the store.
But now i know why this is wrong... My models can come from different source, like:
```
/users/:id/assets
/pages/:id/assets
```
So there is a problem if i get asset from store and delete it, what asset do i deleting?
The last one cached! It's wrong...
So either store should test uniquness by id and url
Or i should disable caching all together...

Any ideas? Please help...

**Comment by bpatram** [comment]
Closing due to age

**Comment by USvER** [comment]
@bpatram my project in production with this bug for two years, but since it's not my pain anymore it's ok!

I think this bug still valid.
