### ISSUE TITLE
Collection not getting initialized properly

### ISSUE THREAD

**Issue by nitinhayaran** [PaulUithol/Backbone-relational#488]
When we have multiple relations on a single model, it looks like one collection is not getting initialized properly.

have a look at following code:
```
var Leaf = Backbone.RelationalModel.extend({

});
var Branch = Backbone.RelationalModel.extend({
    relations: [{
        type : Backbone.HasMany,
        key  : 'leaves',
        relatedModel: Leaf,
        reverseRelation : {
          key : 'branch'
        }
    }],
});
var Root = Backbone.RelationalModel.extend({
  relations: [{
      type : Backbone.HasMany,
      key  : 'branches',
      relatedModel : Branch,
      reverseRelation : {
        key : 'root'
      }
  },{
      type : Backbone.HasMany,
      key  : 'leaves',
      relatedModel: Leaf,
      reverseRelation: {
        key : 'root'
      }
  }],
});



var obj = {
  id : 1,
  title : 'root',
  branches : [{
      id : 1,
      title : 'branch',
      leaves : [{
          id : 1,
          title : 'leaf',
          branch : 1,
          root : 1
      }]
  }]
};

var root = new Root(obj);
alert(root.get('title'));
alert(root.get('branches').at(0).get('leaves').at(0).get('root').get('title')); // returns root object
alert(root.get('leaves').length); // returns 0; shouldn't this be 1
```

I have also setup a jsfiddle for the same at http://jsfiddle.net/ngogq4kw/

**Comment by dantenetto** [comment]
From what I could understand, it seems fine to me. Your plain object doesn't have a leaves attribute directly from root. What you have will only work if branch and leaf are siblings in the same hierarchical level.
If what you expected to happen was having a relation created between leaf and root based on the "root: 1" property, then it would require a lookup in every reverseRelation available for every attribute from related objects, and even though, I don't think that would be the behavior expected by most of the people using the library. Imagine if you have a hierarchical composition using the same property name as the reverseRelation, it would simply broke.

check your jsfiddle
e.g: http://jsfiddle.net/ngogq4kw//1/
