### ISSUE TITLE
findOrCreate with non-idAttribute id

### ISSUE THREAD

**Issue by thejameskyle** [PaulUithol/Backbone-relational#491]
I'm also using Backbone-Tastypie which sets the `idAttribute` to the `resource_uri`. Which is good for Tastypie's purposes, but makes it awkward to use `findOrCreate`.

Most of the time when I need to call `findOrCreate` I just have an `"id"` attribute, so needing to construct a `resource_uri` is awkward and error-prone.

```js
MyModel.findOrCreate('/api/v1/model/' + 1);
```

I'd rather be able to use the normal `"id"` attribute like this:

```js
MyModel.findOrCreate({ id: 1 });
```

as such I've modified `Relational.store.find` to be: 

```js
Backbone.Relational.store.find = function( type, item ) {
  var id = this.resolveIdForItem( type, item ),
      coll = this.getCollection( type );

  // Because the found object could be of any of the type's superModel
  // types, only return it if it's actually of the type asked for.
  if ( coll ) {
    var obj;

    if ( id ) {
      obj = coll.get( id );
    } else {
      obj = coll.findWhere( item ); // <<<<<
    }

    if ( obj instanceof type ) {
      return obj;
    }
  }

  return null;
};
```

I think it'd be good if this behavior was added. Thoughts?

**Comment by fu-raz** [comment]
I think this is just what I need. I would like to see this added.

**Comment by thejameskyle** [comment]
Closing this as part of cleaning out old issues. Feel free to reopen this.
