### ISSUE TITLE
no method "findModel" when invoking findOrCreate

### ISSUE THREAD

**Issue by tjwebb** [PaulUithol/Backbone-relational#507]
I can create and operate on all other aspects of my model just fine. I'm extending from `Backbone.RelationalModel`. But when I invoke `Model.findOrCreate()` (statically) I see this error:
```
Possibly unhandled TypeError: Object [object Object] has no method 'findModel'
  at new Backbone.RelationalModel.Backbone.Model.extend.findOrCreate (/home/tjwebb/workspace/sails-backbone-client/node_modules/backbone-relational/backbone-relational.js:1834:21)
```

**Comment by Neopallium** [comment]
FYI - for others that run into this problem.  This error cost me a few hours.  I hope this helps others.  Sorry for commenting on a closed issue.

Don't do this:

    var val = new Model.findOrCreate({ id: id });

Do this:

    var val = Model.findOrCreate({ id: id });
