### ISSUE TITLE
Bug in extending RelationalModels?

### ISSUE THREAD

**Issue by tiborsaas** [PaulUithol/Backbone-relational#521]
Hello,

I have the following model that extends through two models, one abstract model which has some common methods and properties. That's a `Backbone.Model`. Then the abstract is extended with a specific model, which you see as `VideoClipModel` for example.

	var Clip = Backbone.RelationalModel.extend({
		idAttribute: 'cid',
		constructor: function (attributes, options) {
			var classes, selectedClass;
			classes = {
				video: VideoClipModel,
				image: ImageClipModel,
				audio: AudioClipModel
			};
			selectedClass = classes[ attributes.type ];
			// inherit all methods and properties from the selected class
			// including it's inherited methods and props (from abstract)

			_.forIn(selectedClass.prototype, function (value, key) {
				this[key] = value;
			}, this);

			Backbone.RelationalModel.apply(this, arguments);

			classes = null;
		}
	});

I pass Clip as `relatedModel` when setting up relations.

The whole setup works great while managing only one collection, but when I add a second one, an audioCollection, then it's simply not created.

![bugga](https://cloud.githubusercontent.com/assets/342688/7220809/7ad04d60-e6d5-11e4-972e-0693e110f730.PNG)

Setup of relations:

		relations: [{
			type: Backbone.HasMany,
			key: 'videoCollection',
			relatedModel: Clip,
			collectionType: ClipCollection,
			includeInJSON: includeInJSON
		},{
			type: Backbone.HasMany, // Use the type, or the string 'HasOne' or 'HasMany'.
			key: 'audioCollection',
			relatedModel: Clip,
			collectionType: ClipCollection,
			includeInJSON: includeInJSON
		}],

What's interesting is that if I replace the `Clip` in the audioCollection with a separate AudioClip, like this:

	var AudioClip = Backbone.RelationalModel.extend({
		idAttribute: "cid",
		initialize: function(){
		}
	});

then it works just fine.

I use version 0.8.6

**Comment by bpatram** [comment]
Can you create a jsfiddle to demonstrate your issue? You're doing some custom stuff in that constructor with inheriting properties that is most likely causing an issue when setting up the relation or registering to the store.

**Comment by bpatram** [comment]
I am closing this issue due to its age and lack of response.
