### ISSUE TITLE
is this project no longer maintained?

### ISSUE THREAD

**Issue by tjwebb** [PaulUithol/Backbone-relational#523]
I see a ton of open issues, and no response from the maintainer on most of them. Also no PRs have been merged which alter the codebase in over 6 months. @PaulUithol if you're looking for a new maintainer, I can look around

**Comment by PaulUithol** [comment]
I've been in Tanzania for the last three months, with (very) spotty internet connections and basically other priorities. I'll be back home in two weeks, and plan to start picking up on some of the slack then.

However, if you know someone that'd be willing to help out on at least some of the issues (a lot of them are also more usage questions, which I don't get around to), I'd be more than happy to welcome them!

**Comment by tjwebb** [comment]
We should also recognize that there are a number of PRs that are pretty reasonable, and have no comments and are not merged. From my experience also maintaining an [open-source project](https://github.com/balderdashy/sails), just labeling issues can go a long way toward giving people cues as to what PRs have a snowball's chance of being merged, and can yield more contributions.
