### ISSUE TITLE
Saving model to server with `patch: true` not working with Backbone-relational?

### ISSUE THREAD

**Issue by benmcmaster** [PaulUithol/Backbone-relational#527]
I am saving a model with `patch:true` and passing in only the elements that I want to save. However, backbone + backbone relation is sending the entire model. `isNew` is false because the model has an id. Is anyone else seeing this?

**Comment by PaulUithol** [comment]
This has been working for me, so it's probably something else in your code. Could you try minimizing your case?

**Comment by benmcmaster** [comment]
@PaulUithol thanks for getting back. I ended up doing a hacky work-around by using a temporary non-relational model to save the data to the server. Then set the response to the relational model.

I will try to minimize the case this week. Thanks!

**Comment by PaulUithol** [comment]
Test coverage does seem to be lacking though, for `patch`. I'll also try to get  few of those in.

**Comment by bpatram** [comment]
Seeing as this issue is over a year old I am closing it. I will re-open if a minimized use case can be shared with us or a PR with additional tests is sent.
