### ISSUE TITLE
can not get the reverseRelation model by using model.get("reverseKey")

### ISSUE THREAD

**Issue by anianj** [PaulUithol/Backbone-relational#537]
Hi all,

I have two models like the following
```
var SearchResultSet = module.exports = Backbone.RelationalModel.extend({
    relations: [{
        type: Backbone.HasMany,
        key: 'results',
        relatedModel: SearchResultModel,
        reverseRelation: {
            key: 'belongsTo'
        }
    }]

});
var SearchResultModel = module.exports = Backbone.RelationalModel.extend({
});
```
And i use the following information to populate them.
```
{
          "type": "destination",
          "displayName": "DESTINATIONS",
          "results": [
              {"name": "Newcastle"},
              {"name": "New York"},
              {"name": "New Plymouth"},
              {"name": "New Zealand"}
          ]
      }
```
but when i want to use searchResult.get("beblongsTo") to get a refrence from SearchResultModel to SearchResultSet, i got null. can you help? thanks

**Comment by gmcnaughton** [comment]
@anianj I'm wasn't able to reproduce your issue on  backbone-relational 0.10.0.

Here's a gist of a sample page with your code: https://gist.github.com/gmcnaughton/8f6eae7ee88631c5a2011765570026b6

In your comment, you put `searchResult.get("beblongsTo")` -- was it possibly just a typo?  (It should be `searchResult.get("belongsTo")` I think)

**Comment by feeekkk** [comment]
yeah this should be closed, it is more than likely an implementation error. Works fine on my end
