### ISSUE TITLE
Related collections are not reset

### ISSUE THREAD

**Issue by mauron85** [PaulUithol/Backbone-relational#539]
Description:
When master collection is reset, related collections are still holding references to models, that where removed from master collection. 

See [jsfiddle](http://jsfiddle.net/mauron85/b6nw2fxt/) for example.

Scenario:
Two models: Route and User
Two collections: Routes and Users
User hasMany reverse relation to Route 

Expected:
When Routes collection is reset, User.routes should be reset too and have length of 0.

Actual:
When Routes collection is reset, collection User.routes is not and it is still containing models, that where removed from Routes collection..

How to reproduce:

http://jsfiddle.net/mauron85/b6nw2fxt/

**Comment by mauron85** [comment]
Found this comment. But what kind of warnings?

```
/**
 * Reset the `store` to it's original state. The `reverseRelations` are kept though, since attempting to
 * re-initialize these on models would lead to a large amount of warnings.
 */
```

**Comment by bpatram** [comment]
I do not believe your assumptions are true. Reseting a collection only removes the models from that collection, not the store or other collections. If you were to *destroy* those models in the collection then all other collections with references to those models would no longer contain them.

[Here is an updated example of your JSFiddle](http://jsfiddle.net/b6nw2fxt/3/) that demonstrates what I am saying.
