### ISSUE TITLE
Cloned models come without 'id' attribute

### ISSUE THREAD

**Issue by coderlex** [PaulUithol/Backbone-relational#548]
The overriden clone() function doesn't copy 'id' attribute of a source model. Even more it specially removes the attribute from the result. It must not.

**Comment by bpatram** [comment]
Cloning a model and it's `id` would break how the cache/store works. It uses the model type and its `id` to do lookups and ensure that when you request a model using `find` or `findOrCreate` you return the same instance of the model.
