### ISSUE TITLE
Set event handler in Model initialize?

### ISSUE THREAD

**Issue by Jakobud** [PaulUithol/Backbone-relational#549]
Is it possible to set a Backbone event handler in the model's `initialize` function that listens for changes to a relation? For example:

This doesn't seem to work:
```
var Whatever = Backbone.RelationalModel.extend({
				initialize: function(){
					this.on('change:something', this.somethingChanged);
				},
				somethingChanged: function(model, options) {
					console.log("something changed");
				},
				relations: [{
					key: something,
					.......
				}]
});
```

But using just `change` instead of `change:something` then it will work. Also, you can obviously set the `.on('change'...` handler after creating the object:

```
var myObject = new Whatever();
myObject.on('change:something', myObject.somethingChanged);
```

Anyways, is it possible to define this in the `initialize` function or not? Is it not possible because the property hasn't been defined yet when `initialize` runs?

**Comment by bpatram** [comment]
Yes, this is possible. Even using normal Backbone Models. The properties/attributes do not need to be defined before calling `initialize

---
Below is an example:
```javascript
var User = Backbone.RelationalModel.extend({});

var Video = Backbone.RelationalModel.extend({
	defaults: {
		title: "Utitled Video"
	},
	relations: [
		{
			type: 'HasMany',
			key: 'commenters',
			relatedModel: User
		}
	],
	initialize: function() {
		this.on('add:commenters', this.onNewCommenter);
		this.on('change:name', this.onChangedName);
	},
	onNewCommenter: function() {
		console.log("new commenter!");
	},
	onChangedName: function() {
		console.log("new name!");
	}
});

var userA = new User({});

var video = new Video({});

video.get("commenters").add(userA); // will log "new commenter!"
video.set({ name: "changed name" }); // will log "new name!"
```

**Comment by bpatram** [comment]
Sorry, I misread some of your original question. Let me clarify

Yes, this is possible, at least with HasMany relations. Collections are created when the relation is created which happens before `initialize` is called. This means you can bind to that collection at run time. However, if you were to completely replace that model's collection with another you would need to rebind to its events.

To support HasOne and for swapping collections in a HasMany:
You can listen to `relational:change:[key name]` events and use those to bind to the newly set Collection or Model change events. That will allow you to swap out Collections and Models without having to manually bind to their events after calling `set`.

Below is an example:
```javascript
var User = Backbone.RelationalModel.extend({});

var Video = Backbone.RelationalModel.extend({
	defaults: {
		title: "Untitled Video"
	},
	relations: [
		{
			type: 'HasMany',
			key: 'commenters',
			relatedModel: User
		}
	],
	initialize: function() {
		this.on('add:commenters', this.onNewCommenter);
		this.get('commenters').on('change', this.onChangeCommenter);
	},
	onNewCommenter: function() {
		console.log("new commenter!");
	},
	onChangeCommenter: function() {
		console.log("changed child commenter");
	}
});

var userA = new User({});

var video = new Video({});

video.get("commenters").add(userA); // will log "new commenter!"
userA.set({ name: "new name" }); // will log "changed child commenter"
```
