### ISSUE TITLE
Backbone Relational dealing with model instances with the same ID

### ISSUE THREAD

**Issue by newtonianb** [PaulUithol/Backbone-relational#557]
My scenario is quite simple

 1. **User 1** can be logged in 
   -  represented by a model instance with keys **Name**, **PrivacySetting**
 2. **User 1** can have a profile page and can browse to it (model with keys Name, Photo, Location, Gender, Profession)
   -  represented by a model instance with keys **Name**, **Photo**, **Location**, **Gender**
 3. **User 1** can have comment posted on his own User 1 page (model with keys Name, Photo, Date)
   -  represented by a model instance with keys **Name**, **Photo**, **Reputation**

In the above scenario we are dealing with one loaded page with a potential of 3 User model of the same ID but requiring completely different key/values! Since each gets loaded in its own distinct ajax requests, the app is playing cat and mine and keeps overriding the data of all the User instances of id 1.

I am now faced with a gigantic spaghetti code due to backbone relational recycling. 

The flow of the app is

  -  User 1 loads the app (user.fetch() @ http://host/user/session)
  -  User 1 loads his profile (user.fetch() @ http://host/user/1)
  -  Comments for User 1 are fetched (user.fetch() @ http://host/user/1/comments)

[![enter image description here][1]][1]

  [1]: http://i.stack.imgur.com/c450y.jpg

What I am supposed to do in this scenario?

    class User extends BackboneRelational
    
    class Comment extends BackboneRelational
      relations: [
        {
          type: Backbone.HasOne
          key: "user"
          relatedModel: User
        }
      ]
    
    class CommentCollection extends Collection
      model: Comment

**Comment by jekuno** [comment]
The most simple solution is to have one user model which keeps track of all of your attributes (e.g. Name, Photo, Location, Gender, PrivacySetting and Reputation).
You use three different views to deliver a specific reduced set of attributes to the three
templates. You use templateHelpers to prepare those data to be displayed in your three different view templates.

**Comment by bpatram** [comment]
I am closing as this ticket was opened almost a year ago. 

@newtonianb If you are still having troubles please open a new ticket stating what version of Backbone-relational you are using as well as sending a jsbin/codepen/jsfiddle demonstrating your issue or use case (please see the contribution guidelines for more information).
