### ISSUE TITLE
Backbone 1.3.2 support

### ISSUE THREAD

**Issue by philfreo** [PaulUithol/Backbone-relational#563]
http://backbonejs.org/#changelog

I can see some of the changes especially like `options.changes` potentially changing how BBR should work (perhaps simplifies things)

Overall it'd be great if there was a clear indication in the README or on http://backbonerelational.org/ which versions of Backbone BBR have been specifically tested / optimized for already, so that when a new version comes out there's no guessing.

**Comment by bpatram** [comment]
@philfreo I completely agree. We will need to update the test suite to test against multiple combinations of Backbone. As of BBR version 0.10.0 the dependency uses `>=1.2.1` which will most likely cause issues when newer versions of backbone are released (like 1.3.2). I have not ran any tests on 1.3.2 yet to verify if it contains anything that might break BBR.

Let's plan in the next release to get backbone support to be between 1.2.x and 1.3.2.

**Comment by jeremymlane** [comment]
I ran tests on Backbone 1.3.1 - 1.3.3 and everything looks good (with one minor update). Will submit a pull request.
