### ISSUE TITLE
using toJSON to serialize data

### ISSUE THREAD

**Issue by tjaartvdwalt** [PaulUithol/Backbone-relational#565]
I am using `Backbone-relational` with `Marionette`. 

I recently upgraded to a prerelease of Marionette v3, and found that my sub views were not rendering properly anymore.

For example instead of:
```handlebars
{{foo.bar}} 
```
I now need to have:
```handlebars
{{foo.attributes.bar}} 
```
I opened a bug with Marionette (marionettejs/backbone.marionette#2984) and there were 2 important comments:

> Backbone relational overides the toJSON of models, v2 used this as the default serializeData

and the response

> Well toJSON is not supposed to be for view rendering. 

I wonder if this is something that can be changed in Backbone-relational?

**Comment by bpatram** [comment]
Looking at the changes to Marionette you should be able to override the `serializeModel` or `serializeCollection` function on your views. Below is what I imagine will fix your issue, but I have not tested this.

```javascript
import { ItemView } from 'backbone.marionette';
export default ItemView.extend({
    ...
    serializeModel(model) {
        return model.toJSON();
    },
    serializeCollection(collection) {
        return collection.toJSON();
    }
    ...
});
```

That being said, this is just a temporary solution (if it works). I will investigate a better solution to this issue.

**Comment by lddubeau** [comment]
I've just done a migration from Marionette 2 to 3. The code I used to work around the problem follows. I did not feel like hunting for individual classes the needed the change so I made it a global thing. `Mn` is Marionette.

```
  Mn.View.prototype.serializeModel = function serializeModel() {
    if (!this.model) {
      return {};
    }

    return this.model.toJSON();
  };

  Mn.View.prototype.serializeCollection = function serializeCollection() {
    if (!this.collection) {
      return {};
    }

    return this.collection.toJSON();
  };
```

**Comment by bpatram** [comment]
I'm not sure exactly what we can do about this from our end since this is the behavior of Marionette which differs from basic backbone views. At this time it seems out of scope for this library to override default behavior in another.
