### ISSUE TITLE
JSBin example

### ISSUE THREAD

**Issue by jekuno** [PaulUithol/Backbone-relational#568]
I've set up a JSBin example which can be used as a template to reproduce potential issues with `Backbone-relational`. What do you think about adding this link to the docs?

https://jsbin.com/kixiritoka/1/edit?html,js,console

**Comment by bpatram** [comment]
@jekuno I've been planning on adding an extra contributing section to the read me or as its own file for a while now. This is definitely a step in the right direction to make it easier for new people to contribute! My initial example is on [jsfiddle](http://jsfiddle.net/4223kp5e/1/) right now, but I'd be happy to migrate that to JSBin as well.
