### ISSUE TITLE
Rename Backbone-relational to backbone.relational

### ISSUE THREAD

**Issue by bpatram** [PaulUithol/Backbone-relational#569]
Almost all other Backbone libraries use a dot (.) instead of a dash (-).

Thoughts?

**Comment by philfreo** [comment]
Two very popular ones are backbone-super and backbone-forms which both don't

**Comment by bpatram** [comment]
It's definitely an ascetic thing. Looking at http://backplug.io/ the majority of other libraries use a dot. The dot would also better reflect that we are using (in the next release) our own namespace `Backbone.Relational.*`. I know in my own stack of packages I use for projects bbr is always the odd one out by using the dash.

I know backbone.marionette (another very popular one) uses a dot, but they will soon be renaming themselves as just marionette (so it may be a moot point).

**Comment by feeekkk** [comment]
+1 if we will be switching to our own namespace, otherwise I'd say it is moot considering the likes of marionette, backbone-poller, backgrid-* etc.

**Comment by bpatram** [comment]
We will keep the same name, using a dash not a dot!
