### ISSUE TITLE
Double imports for using with webpack

### ISSUE THREAD

**Issue by okovpashko** [PaulUithol/Backbone-relational#570]
Hello.

I'm using webpack + babel in my project and I found that `require('backbone-relational')` call doesn't return module for BackboneRelational object and I have to use two 'import' calls (converted by babel in 'require') in every relational model of my application:
```
import BackboneRelational from 'backbone-relational';
import {RelationalModel} from 'backbone';
let MyModel = RelationalModel.extend({});
```
Instead I would like using only one import statement:
```
import {RelationalModel} from  'backbone-relational';
let MyModel = RelationalModel.extend({});
```
Is it possible to update UMD loader for that?

**Comment by bpatram** [comment]
As of version 0.10 you will need to import backbone then import backbone
relational. Backbone relational will modify the backbone imported object.
So try something like this:

```javascript
import Backbone from 'backbone';
import from 'backbone relational';

export default Backbone.RelationalModel.extend(...);
```

**Comment by bpatram** [comment]
As of version 0.10 you will need to import backbone then import backbone
relational. Backbone relational will modify the backbone imported object.
So try something like this:

```javascript
import Backbone from 'backbone';
import from 'backbone relational';

let MyModel = Backbone.RelationalModel.extend(...);
```

**Comment by okovpashko** [comment]
@bpatram I understand that Backbone relational modifies Backbone, but many backbone libraries do that and exports itself as the module. Any `require('backbone')` inside the library will return the same Backbone object as outside and patched once Backbone will be available from outside with all patches.
Here is an example from Backbone.ModelBinder UMD definition:
```
if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['underscore', 'jquery', 'backbone'], factory);
} else if(typeof module !== 'undefined' && module.exports) {
    // CommonJS
    module.exports = factory(
        require('underscore'),
        require('jquery'),
        require('backbone')
    );
} else {
    // Browser globals
    factory(_, jQuery, Backbone);
}
```
It requires Backbone and patches it iside factory function, but it also defines module.exports.
Isn't is possible to use such UMD definition in Backbone relational?

**Comment by bpatram** [comment]
In an upcoming release we will start to export our own object as well as modify Backbone within our own namespace (see #566 and #559). 

Until then I would suggest creating the following shim:

```javascript
// relational-shim.js
import Backbone from 'backbone';
import 'backbone-relational';

export default {
  Model: Backbone.RelationalModel,
  Collection: Backbone.Collection,
  HasMany: Backbone.HasMany,
  HasOne: Backbone.HasOne,
  store: Backbone.Relational.store
}
```

Then use it like the following:

```javascript
import { Model, Collection } from 'relational-shim';

let myModel = Model.extend(...);
let myCollection = Collection.extend({ model: myModel, ... });
```

**Comment by okovpashko** [comment]
Thanks a lot!

**Comment by lvv83** [comment]
Hello!
I just want to say, that `import` directive for **default** export should be like this

```javascript
import Shim from 'relational-shim';

let myModel = Shim.Model.extend(...);
let myCollection = Shim.Collection.extend({ model: myModel, ... });
```

Thanks!
