### ISSUE TITLE
Doesn't play nice with CoffeeScript class/extends syntax.

### ISSUE THREAD

**Issue by DouweM** [PaulUithol/Backbone-relational#91]
When using Backbone-relational with [CoffeeScript](coffeescript.org/), creating a `Backbone.RelationalModel` subclass using the CoffeeScript [`class`/`extends` syntax](http://coffeescript.org/#classes) doesn't work properly, as the reverse relation initialization in [`Backbone.RelationalModel.extend()`](https://github.com/PaulUithol/Backbone-relational/blob/master/backbone-relational.js#L1310) is never called. Note that this syntax _does_ work when subclassing `Backbone.Model`, as this doesn't have any special logic in its `.extend()` method.

CoffeeScript users currently have to use:

``` coffeescript
Person = Backbone.RelationalModel.extend
  relations: [
    # etc.
  ]
```

instead of:

``` coffeescript
class Person extends Backbone.RelationalModel
  relations: [
    # etc.
  ]
```

Losing the slightly nicer syntax isn't so bad, weren't it for the fact that this means you can't use cool CoffeeScript things like `super` and the `@static: value` syntax for setting static variables either.

This isn't a problem with Backbone-relational per se, but it would be nice to find a way around this problem so that CoffeeScript users will be able to use the combination of Backbone-relational and CoffeeScript to the fullest extent. This issue is here so that hopefully someone will come up with a nice solution. Maybe it'll be me, but I thought I'd share it here with the community so that others are aware of this not working and can think about a solution as well.

In the mean time, I think it'd be a good idea to place a Note in the README pointing out that the CoffeeScript syntax doesn't work yet, so that people won't get a nasty surprise when their reverse relations aren't working properly. There are a lot of people that could be having problems with this, seeing how many people are using Backbone.js with CoffeeScript: [Google search for "backbone coffeescript"](http://www.google.com/search?client=safari&rls=en&q=backbone+coffeescript&ie=UTF-8&oe=UTF-8).

**Comment by elgubenis** [comment]
after creating or after defining?
